name: Magma Build Docker Image Bazel Base & DevContainer
on:
  workflow_dispatch: null
  push:
    branches:
      - master
pull_request:  
    branches:
      - master
    types: [ opened, reopened, synchronize ]
jobs:
  push_to_registry:
    if: github.repository_owner == 'akhilamoyila9'
    
